### PR TITLE
Fix block diff and block trend when state flips (e.g. Georgia)

### PR DESCRIPTION
**Pull request by spraot**
After Georgia was flipped, trend number should be flipped too

### CODE REVIEW

**Comment by Enivex** [comment]
The algorithm needs to be fixed. Just changing the number in the text file solves nothing.

**Comment by spraot** [comment]
You're right, should be fixed now though

**Comment by spraot** [comment]
Fixes #210 by the way

**Review by JJ — APPROVED** [review]
I would say this looks fine. Closing mine.

**Comment by jimm89** [comment]
Nice work, @rachetfoot

**Review by somethingnew2-0 — APPROVED** [review]

**Review by frewsxcv — APPROVED** [review]
thank you so much for fixing this! 🎉

**Pull request merged**
