### PR TITLE
collapsible tables

### PR DESCRIPTION
**Pull request by WarrenBuffering**
tables are collapsible

### CODE REVIEW

**Comment by alex** [comment]
Is this necessary now that we have the collapse button at the top?

**Comment by WarrenBuffering** [comment]
I guess I assumed you and @frewsxcv were working together on this and he mentioned it in another comment

>agreed with the decision to close. it'd be interesting seeing other states! but it gets noisy because we don't currently have collapsing tables, or an easy way to see just the battleground data amongst the other states

**Comment by WarrenBuffering** [comment]
Oh apologies, I misunderstood your question. I guess I'll leave that up to you.

**Comment by WarrenBuffering** [comment]
actually looking at things on mobile it would be pretty nice if I could collapse the ones I'm not actively viewing.

**Comment by bojanrajkovic** [comment]
LGTM but can you rebase out the changes to the generated HTML? You should only commit changes to the template. If you can't make it work, I probably can.

**Comment by WarrenBuffering** [comment]
Sure thing. Give me a sec

**Comment by WarrenBuffering** [comment]
My bad, didn't mean to commit the actual html file. Should be g2g now

**Comment by WarrenBuffering** [comment]
More conflicts. If you guys are ready to merge it at some point lmk and I can resolve. Otherwise I'm just gonna leave it.

**Pull request merged**
