### PR TITLE
Fixed sticky table headers

### PR DESCRIPTION
**Pull request by 2CATteam**
Slightly changed the CSS on the table header to fix the issue where the top line of the table header does not properly stick to the top of the window

### CODE REVIEW

**Comment by fractionalhare** [comment]
any chance of getting a screenshot on this change? would be good for UI changes

**Comment by 2CATteam** [comment]
Can you explain what you mean? I just adjusted spacing and added an !important note on the relevant CSS setting.

Here's the current live version on my end (Tested on a few different browsers):
image

Here's after my change (Also on different browsers)
image

**Comment by 2CATteam** [comment]
Here's the difference between CSS the live version and this change (Top current, bottom mine):

image
image

As far as I can tell, regardless of zoom levels, this change keeps proper spacing, though the 3.6 may need to be slightly changed.

**Comment by bojanrajkovic** [comment]
Hmm, doesn't work for me on Safari.

image

**Comment by bojanrajkovic** [comment]
I merged #130 in favor of this, since it works more correctly.

**Comment by 2CATteam** [comment]
Well, it worked fine for me on Safari, but the current fix looks better than mine did anyway! Thanks for your work.

**Pull request closed without merging**
