### PR TITLE
add id so I can link directly to a row

### PR DESCRIPTION
**Pull request by graingert**
###### Changes

- [x] Ensured that you have [rebased your branch](https://stackoverflow.com/a/7244456) with this repo's latest master branch.
- [ ] Ensured that relevant issues are linked, if this PR resolves any outstanding.
- [ ] Added a screenshot for all UI changes (you can drag the file into this edit box and it will be uploaded).
- [ ] Ensured that changes to auto-generated files have not been committed; in particular, `*.html`, `*.csv` and `*.json` files.

### CODE REVIEW

**Review by bojanrajkovic — CHANGES_REQUESTED** [review]
Won’t the timestamp be inconsistent, so the link would keep changing all the time?

**Comment by graingert** [comment]
@bojanrajkovic isn't the timestamp historical?

**Comment by bojanrajkovic** [comment]
No, it’s the scrape timestamp for the current run. It would change every run, AFAICT.

**Comment by graingert** [comment]
@bojanrajkovic once a row is added, it's not updated:
https://github.com/alex/nyt-2020-election-scraper/commit/8b0933ff4bb74e477efb72758e39d339fdd116d6#diff-46d4fb93617cbbf767d42a55d3729dbd6f38900c2b3dfecb826bc657dc4e3be0R851

**Review by bojanrajkovic — APPROVED** [review]

**Comment by bojanrajkovic** [comment]
Oh god I'm an idiot. This whole time I was confusing rows w/ the state header. That's what I get for reviewing PRs while still in bed.

**Pull request merged**
