### PR TITLE
Including FL, MI and WI

### PR DESCRIPTION
**Pull request by WarrenBuffering**
Included the states of Florida, Michigan and Wisconsin

### CODE REVIEW

**Comment by alex** [comment]
These states have already been called. We're not including states where we believe we conclusively know the results.

**Comment by frewsxcv** [comment]
agreed with the decision to close. it'd be interesting seeing other states! but it gets noisy because we don't currently have collapsing tables, or an easy way to see just the battleground data amongst the other states

**Comment by WarrenBuffering** [comment]
For that matter, Arizona has also been officially called by some, as well as Nevada by a few others. These 3 states are still very close. For example, Wisconsin still has an estimated 56,887 votes left with Trump only trailing by 20,558. I can look up the other two if you'd like, but I think these 3 states are substantial and entirely still in play

I understand not wanting to overload the users, but these three states still appear to be far from decided. I will double check on Florida and Michigan to be sure @frewsxcv , but I believe Wisconsin is definitely worth of being added.

**Comment by WarrenBuffering** [comment]
Looks like you're both right about Florida and Michigan, but I believe Wisconsin is worthy of inclusion.

**Pull request closed without merging**
