### PR TITLE
Sort by Suspense

### PR DESCRIPTION
**Pull request by blaine**
(hurdle - block trend) * precincts reporting

### CODE REVIEW

**Comment by blaine** [comment]
per https://twitter.com/dansinker/status/1324536884601720834?s=20

**Comment by blaine** [comment]
(ideally this would incorporate some recency metric, but my python is extremely rusty and the single 30 second attempt at datetime math I made didn't work)

**Comment by bojanrajkovic** [comment]
I'm a 👎 on this change -- I like the idea of a volatility metric, but it should be part of the state header or something, and not a sort order. Using it for sorting means the file could change in between runs/reloads of the webpage, which is super jarring.

**Review by bojanrajkovic — CHANGES_REQUESTED** [review]
See other comment.

**Comment by thomasdesr** [comment]
Hey!

Thanks for the PR! This would cause the states to shuffle around based on the value of suspense. I'm worried that'd cause a lot of shuffling. I'm curious if you have any suggestions on how to avoid that?

**Comment by blaine** [comment]
Updated the metric - the goal was to have the most relevant states up at the top of the page, verus the alphabetic sort. Maybe some kind of rolling average to keep things relatively stable? In practice, the tighter the race the higher the 'suspense' so in theory the sort should be relatively stable, or switch between two tight races?

**Comment by titanous** [comment]
Hi @blaine! Thanks for the suggestion! We've decided not to change the sort, but are going to be defaulting to the collapsed tables, so everything is easy to access.

**Pull request closed without merging**
