### PR TITLE
Math better. Closes #194

### LINKED ISSUE #194: Error in Hurdle Percentage Estimates
So I'm not much of a coder but decently good with numbers and I noticed a problem with the way the program is calculating the hurdle figures. I've run some calculations based on its numbers and I'm reasonably certain it's deriving the hurdles from this equation:

H = (100%)(D + R)/(2R)

where H = estimated hurdle percentage, D = vote differential, and R = estimated votes remaining.

This seems fairly accurate, but it's actually wrong. Let me explain why with the following system of equations:

L - W = D
L + W = R

where L = # of currently losing candidate's (Trump or Biden) remaining votes if they make the hurdle, W = # of currently winning candidate's (Trump or Biden) remaining votes if the other one makes the hurdle, and D and R are the same as what I defined them as before. 

The rationale here is pretty simple. If the currently losing candidate is to beat the currently winning candidate, then in the remaining votes, the losing candidate must beat the winning candidate by a margin greater than or equal to the current vote differential, D (i.e., the first equation). And obviously Biden and Trump's remaining votes have to sum to the total number of remaining votes, R (i.e., the second equation).

Solving by elimination, we get:

2L = D + R
L = (D + R)/2

Then we just divide L by R and multiply the quotient by 100 percent to get the hurdle percentage, H:

H = (100%)(D + R)/(2R)

As you can see, this is exactly the same equation that I said I believe the program is using now. So where's the error? It's actually in our original system of equations. Remember when I said Biden and Trump's remaining votes have to sum to the total number of remaining votes? That's only true if every single vote was cast for Biden or Trump. We're ignoring the small fraction of non-Biden, non-Trump votes (i.e., third-party, independent, and write-in votes). 

There's no perfect way to account for these votes since we don't know what the proportion of non-Biden, non-Trump votes will be among the remaining votes. However, we can approximate it by calculating that proportion for the votes already counted. Scaling down the right side of our second equation on this basis, our amended system of equations is:

L - W = D
L + W = R(B + T)/S

where B = # of current Biden votes, T = # of current Trump votes, and S = sum of all current votes.

Reworking the math, we find:

H = (100%)(D + R(B + T)/S)/(2R)

Even though the program's hurdle percentages tended to be only ~0.6 percent off from the ones I calculated using the amended equation, considering how close this race is, I think fixing the error is warranted. And while my equation is also flawed as it assumes the proportion of non-Biden, non-Trump votes won't change, estimating that proportion is far better than disregarding it altogether.

That being said, I'm a coding amateur at best and don't trust myself to work with the files. I'm just putting this out there so that someone who's better at this stuff than I am can make what I assume is a very small edit.

### PR DESCRIPTION
**Pull request by phildini**
###### Motivation
Using math better!
###### Changes
Applying the formula in the linked issue.

- [x] Ensured that you have [rebased your branch](https://stackoverflow.com/a/7244456) with this repo's latest master branch.
- [x] Ensured that relevant issues are linked, if this PR resolves any outstanding.
- [x] Added a screenshot for all UI changes (you can drag the file into this edit box and it will be uploaded).
- [x] Ensured that changes to auto-generated files have not been committed; in particular, `*.html`, `*.csv` and `*.json` files.

## Old math result:
Screen Shot 2020-11-05 at 11 52 52 PM

## New math result:
Screen Shot 2020-11-05 at 11 52 21 PM

### CODE REVIEW

**Review by thomasdesr — APPROVED** [review]

**Comment by eebasso** [comment]
This formula is still incorrect I think. This should be multiplied by a ratio factor of (total votes) / (two party vote). I will show why very soon.

**Comment by eebasso** [comment]
The key assumption is that we assume the third party will get the same % of the remaining vote as they have already.

**Comment by eebasso** [comment]
Why not use the following in line 333?

hurdle = (vote_diff * votes / ((candidate1_votes + candidate2_votes)*votes_remaining) + 1 ) / 2 if votes_remaining > 0 else 0

Here is my reasoning

[Correct Hurdle Formula.pdf](https://github.com/alex/nyt-2020-election-scraper/files/5507669/Correct.Hurdle.Formula.pdf)

**Comment by eebasso** [comment]
Sorry, I'm new to GitHub, I see now that the changes have been implemented to the hurdle formula.

**Comment by saleemrashid** [comment]
@eebasso No worries, thanks for the detailed issue. :heart:

**Pull request merged**
