### PR TITLE
Add the lead margin to state vote counts

### PR DESCRIPTION
**Pull request by xkahn**
###### Changes

- [ ] Ensured that you have [rebased your branch](https://stackoverflow.com/a/7244456) with this repo's latest master branch.
- [ ] Ensured that relevant issues are linked, if this PR resolves any outstanding.
- [ ] Added a screenshot for all UI changes (you can drag the file into this edit box and it will be uploaded).
- [ ] Ensured that changes to auto-generated files have not been committed; in particular, `*.html`, `*.csv`, `*.xml` and `*.json` files.

### CODE REVIEW

**Comment by thomasdesr** [comment]
Hey @xkahn can you include a screenshot of what this would look like?

**Review by bojanrajkovic — CHANGES_REQUESTED** [review]
Can you attach a screenshot of your changes?

**Comment by xkahn** [comment]
Screenshot:
image

**Comment by xkahn** [comment]
> Can you attach a screenshot of your change

@bojanrajkovic The screenshot is above.

**Comment by titanous** [comment]
We've added the vote percentages to the table headers.

**Pull request closed without merging**
