### PR TITLE
add formatting for block leader

### PR DESCRIPTION
**Pull request by onlymattjohnson**
Added a small snippet to add TD class for the leader of the chunk.

Resolves issue #117

### CODE REVIEW

**Comment by onlymattjohnson** [comment]
This is related to issue #117 

https://github.com/alex/nyt-2020-election-scraper/issues/117

**Comment by onlymattjohnson** [comment]
image

**Comment by onlymattjohnson** [comment]
**Note:** same functionality is duplicated in PR #140 - if that PR is merged, please go ahead and close this one.

**Review by bojanrajkovic — CHANGES_REQUESTED** [review]
This is too much color visual noise. We'd consider a bolded winner's name, if you want to try that out and submit some screenshots.

**Pull request closed without merging**
