### PR TITLE
Add link to slackbot

### PR DESCRIPTION
**Pull request by joshcarp**
Hey, I quickly updated the README and the main page to link to the slackbot that i created that links to your website
Lemme know what you think

### CODE REVIEW

**Comment by bojanrajkovic** [comment]
@joshcarp Can you update the template and NOT the generated battleground-state-changes.html file?

**Comment by frewsxcv** [comment]
i'm slightly in favor of not showing this in the HTML. i think we should just keep election related info, along with buttons/text for the site, but i don't feel strongly

**Comment by thomasdesr** [comment]
Maybe another option would be to publish an RSS feed? There's an official bot that could consume an RSS url

**Comment by joshcarp** [comment]
an RSS feed would be great, I just did this as a hack, because I've recently started with making slackbots and it seemed like a fun thing to do

**Comment by joshcarp** [comment]
image
This is what it looks like currently (I'll put trends in soon)

**Comment by joshcarp** [comment]
@bojanrajkovic 
Edited the html template
this is what it looks like: 
image

**Comment by thomasdesr** [comment]
Hey @joshcarp 

The number of slack bots in my daily life definitely testifies to their usefulness 😅 . 

Unfortunately we don't want to be in the position of endorsing anything outside of this repo. If you wanted to contribute an RSS implementation that's something we'd definitely be open to.

**Pull request closed without merging**
