### PR TITLE
Right aligning numbers

### PR DESCRIPTION
**Pull request by calvinkarpenko**
Aligns numbers to the right. Solves #323 
I haven't rebased as I have no idea how to do that. This is my first PR

###### Changes

- [ ] Ensured that you have [rebased your branch](https://stackoverflow.com/a/7244456) with this repo's latest master branch.
- [x] Ensured that relevant issues are linked, if this PR resolves any outstanding.
- [x] Added a screenshot for all UI changes (you can drag the file into this edit box and it will be uploaded).
- [x] Ensured that changes to auto-generated files have not been committed; in particular, `*.html`, `*.csv`, `*.xml` and `*.json` files.

screenshot-chrome-desktop

### CODE REVIEW

**Comment by calvinkarpenko** [comment]
I have no idea what I've just done.
Sorry - I'm relatively new to Github and tried to rebase

**Comment by titanous** [comment]
We decided to revert this change. Thanks for trying to fix it!

**Comment by axlekb** [comment]
I think the original commit here is still good.  Right-aligning numerical columns is usually a pretty standard practice.  Just want to make sure that the `git rebase` issues aren't fogging the good work done here.

https://github.com/alex/nyt-2020-election-scraper/pull/326/commits/0db4e3ea28195246ac7aa2da330d4b38bfae6cd4

**Comment by titanous** [comment]
I cleaned this up and merged in #363.

**Pull request closed without merging**
