### PR TITLE
Add feature to order tables by update time

### LINKED ISSUE #246: Sort tables by last update timestamp in descending order
**Is your feature request related to any of these? We are not pursuing these at the moment.**

[ ] - graphs and data visualizations
[ ] - projections and regression models
[ ] - additional data added to the top of the page

**Is your feature request related to an issue? Please cite the issue.**

Just a minor suggestion to make it easier to find the table containing the last update (when we click on the notification and land on the page, we need to search the last update visually).

**Clearly describe the solution you'd like**

It would be pretty handy to have tables sorted by last updated, so that the table containing the most recent update is always the first in the stack.

### PR DESCRIPTION
**Pull request by fishstik**
image

###### Motivation
- Make it easier to locate recently changed states
- Resolve #246 
- Partially address #51 

###### Changes
- Add feature to order tables by last updated timestamp in descending order
- Allow toggling between this and alphabetical order (pref persists using local storage)
- Alphabetical order is used by default

###### Checklist
- [x] Ensured that you have [rebased your branch](https://stackoverflow.com/a/7244456) with this repo's latest master branch.
- [x] Ensured that relevant issues are linked, if this PR resolves any outstanding.
- [x] Added a screenshot for all UI changes (you can drag the file into this edit box and it will be uploaded).
- [x] Ensured that changes to auto-generated files have not been committed; in particular, `*.html`, `*.csv`, `*.xml` and `*.json` files.

### CODE REVIEW

**Comment by fishstik** [comment]
Note: I haven't tested a7c9ea9, which refreshes the table order feature after live update check, since I am debugging with a local .html file.

**Comment by jjarmoc** [comment]
This works for me locally, but I haven't been able to test it with live updates as the CORS request fails from a file:// URL. Working on it... 

The button text having variable length it moves the others left and right when changing sort orders. I'm not sure that matters, since the tables obviously move around quite a bit too, but it's a little jarring to me. Maybe move the new button to the left of the others?

**Comment by fishstik** [comment]
I ran into the CORS error as well. I edited the fetch to point to the live URL instead of `location` and it starts checking, but it's unable to pull in real changes (which makes sense...I think...)

wrt button position: Since it manipulates the appearance of the tables, I think the new button makes more sense next to the 'Expand/Shrink Tables' button as opposed to the 'Live Update button', so c9a90b5 changes the button text from `A-Z` to `Alphabetically` to keep the button size more even between the two options.

**Comment by jjarmoc** [comment]
I got a decent test in by serving it via a local webserver, modifying the file hashes, and forcing an update in the JS console. It looks to persist across refreshes fine to me.

We should probably get someone else to confirm, since this is a fairly significant change, but I think it looks good. We'll also need to see if it's the sort of the thing the maintainers want, but it's been requested a couple times so I think it makes sense to add.

**Comment by darylantony** [comment]
Oh nice, I'm glad this is on the way.

**Comment by bojanrajkovic** [comment]
We're concerned about how this would deal with live reload changes, and are not sure whether we want the feature at all. If you can do some more testing with live reload to validate that it works, we might reconsider merging this in the future. Thank you for your submission!

**Comment by fishstik** [comment]
Here's a screen recording of a live template update. I'll post a recording of a results update next time it occurs.
template_refresh

**Comment by fishstik** [comment]
...and here's a live results update.
results_refresh

It looks like it plays nicely with live updates.

**Comment by mindrones** [comment]
@bojanrajkovic having the toggle the choice would be on the user no? It seems to me it's working well (thanks @fishstik for implement it!), would you consider merging this?
Thanks for the tool anyway! :)

**Pull request closed without merging**
