### PR TITLE
Use state abbreviations in notification

### LINKED ISSUE #378: Use state abbreviations in notifications
**Is your feature request related to any of these? We are not pursuing these at the moment.**
No it is not :)

- [ ] graphs and data visualizations
- [ ] projections and regression models
- [ ] additional data added to the top of the page
- [ ] changes to the hurdle rate. please see https://github.com/alex/nyt-2020-election-scraper/issues/194; the hurdle rate is not incorrect.

This isn't really a big deal, but currently if enough states add votes you can't necessarily see all of them in the notification:
image

Proposal: Add a `stateToAbbreviation` object that translates state name to state abbreviation (i.e. `"Pennsylvania"` -> `"PA"`), and in the `new Notification` call map over `latestMetadata.states_updated` using that object. The result would be a notification with text "New ballots counted in: PA, GA, AZ".

Happy to open a PR to do this (already have the code though don't know how to compile the template files to test it).

### PR DESCRIPTION
**Pull request by berkowitze**
###### Motivation
Closes #378

###### Changes
**Before:**
image
**After:**
image

- [x] Ensured that you have [rebased your branch](https://stackoverflow.com/a/7244456) with this repo's latest master branch.
- [x] Ensured that relevant issues are linked, if this PR resolves any outstanding.
- [x] Added a screenshot for all UI changes (you can drag the file into this edit box and it will be uploaded).
- [x] Ensured that changes to auto-generated files have not been committed; in particular, `*.html`, `*.csv`, `*.xml` and `*.json` files.

### CODE REVIEW

**Comment by sebsebmc** [comment]
Are American Samoa and Federated States of Micronesia needed here? I don't believe they are in the data we use

Same with Guam, Marshall Islands, etc.

**Review by titanous — APPROVED** [review]

**Comment by berkowitze** [comment]
True, got this object from stackoverflow. Figured extra states couldn't hurt 🤷‍♂️ 

Happy to remove them.

**Comment by sebsebmc** [comment]
DC exists in the 50 state code, so its actually useful, but I believe that the state abbreviation are in the JSON data already so we don't need this translation object at all.

**Comment by berkowitze** [comment]
@sebsebmc the abbreviations are kind of buried in results.json - I feel like it's not worth parsing all of that just to get the abbreviation. Unless the state names are inconsistent over time/don't exactly match the translation object.

**Comment by saleemrashid** [comment]
Thanks for the great pull request! Since `results.json` includes the state abbreviations that we need, I'd prefer to use that instead of hardcoding the abbreviations in the codebase.

I'd like to close this in favor of #380, which hopefully fixes your issue.

**Comment by titanous** [comment]
Superceded by #380

**Comment by berkowitze** [comment]
Makes sense, cheers!

**Pull request closed without merging**
