### PR TITLE
Show sign of hurdle

### PR DESCRIPTION
**Pull request by anxsh**
###### Changes

- [ ] Ensured that you have [rebased your branch](https://stackoverflow.com/a/7244456) with this repo's latest master branch.
- [ ] Ensured that relevant issues are linked, if this PR resolves any outstanding.
- [ ] Added a screenshot for all UI changes (you can drag the file into this edit box and it will be uploaded).
- [ ] Ensured that changes to auto-generated files have not been committed; in particular, `*.html`, `*.csv`, `*.xml` and `*.json` files.

### CODE REVIEW

**Comment by fractionalhare** [comment]
Can you clarify what you mean by the "sign of hurdle"? Like +/-?

**Comment by anxsh** [comment]
Yes.

**Comment by Enivex** [comment]
The hurdle is already "signed". It tells you which candidate is behind.

**Comment by anxsh** [comment]
I see a (-) but not a (+), which made it a little less clear to me.

**Comment by bojanrajkovic** [comment]
I think we're just going to remove this number instead. Thank you for your contribution!

**Comment by anxsh** [comment]
No problem, thanks for putting this together!

**Pull request closed without merging**
