### PR TITLE
Generate an RSS file (#173)

### PR DESCRIPTION
**Pull request by asedeno**
###### Motivation
I want an RSS feed with distilled updates of margins for the latest updates from each battleground state.

###### Changes

- [x] Ensured that you have [rebased your branch](https://stackoverflow.com/a/7244456) with this repo's latest master branch.
- [x] Ensured that relevant issues are linked, if this PR resolves any outstanding.
- [ ] Added a screenshot for all UI changes (you can drag the file into this edit box and it will be uploaded).
- [x] Ensured that changes to auto-generated files have not been committed; in particular, `*.html`, `*.csv` and `*.json` files.

### CODE REVIEW

**Comment by asedeno** [comment]
Sample output:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
 <channel>
  <title>NYT 2020 Election Scraper RSS Feed</title>
  <link>https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html</link>
  <description>Latest results from battleground states.</description>
  <lastBuildDate>Fri, 06 Nov 2020 10:05:06 -0000</lastBuildDate>
  <item>
   <description>Alaska (EV: 3): Trump +51382</description>
   <pubDate>Wed, 04 Nov 2020 23:40:57 -0000</pubDate>
   <guid isPermaLink="false">alaska@1604533257.265</guid>
  </item>
  <item>
   <description>Arizona (EV: 11): Biden +46667</description>
   <pubDate>Fri, 06 Nov 2020 08:37:12 -0000</pubDate>
   <guid isPermaLink="false">arizona@1604651832.105</guid>
  </item>
  <item>
   <description>Georgia (EV: 16): Trump +1805</description>
   <pubDate>Fri, 06 Nov 2020 09:10:39 -0000</pubDate>
   <guid isPermaLink="false">georgia@1604653839.999</guid>
  </item>
  <item>
   <description>North Carolina (EV: 15): Trump +76737</description>
   <pubDate>Thu, 05 Nov 2020 23:03:08 -0000</pubDate>
   <guid isPermaLink="false">north-carolina@1604617388.899</guid>
  </item>
  <item>
   <description>Nevada (EV: 6): Biden +11438</description>
   <pubDate>Thu, 05 Nov 2020 23:24:54 -0000</pubDate>
   <guid isPermaLink="false">nevada@1604618694.828</guid>
  </item>
  <item>
   <description>Pennsylvania (EV: 20): Trump +22576</description>
   <pubDate>Fri, 06 Nov 2020 10:05:06 -0000</pubDate>
   <guid isPermaLink="false">pennsylvania@1604657106.029</guid>
  </item>
 </channel>
</rss>
```

**Review by bojanrajkovic — CHANGES_REQUESTED** [review]
You'll also need to update the GH Actions workflows to:

* Check that there were no changes committed to this static file
* Commit the static file to the repo

**Comment by asedeno** [comment]
Do I? I don't see the csv file being explicitly added in the GH Actions workflow.
I think I just need to rebase, then generate and add an initial xml file, and then the workflow will just take care of things in due course when things change.

edit: nevermind, got it.

**Comment by asedeno** [comment]
@bojanrajkovic all set, I think.

**Pull request merged**
