### PR TITLE
hurdle recalc

### PR DESCRIPTION
**Pull request by xxxmagicxxx**
###### Motivation

	Fix Hurdle Calculation - Issue https://github.com/alex/nyt-2020-election-scraper/issues/206

###### Changes

- [x] Ensured that you have [rebased your branch](https://stackoverflow.com/a/7244456) with this repo's latest master branch.
- [x] Ensured that relevant issues are linked, if this PR resolves any outstanding.
- [x] Added a screenshot for all UI changes (you can drag the file into this edit box and it will be uploaded).
- [x] Ensured that changes to auto-generated files have not been committed; in particular, `*.html`, `*.csv` and `*.json` files.

### CODE REVIEW

**Comment by paulbailey** [comment]
Looks like it fixes #206, and duplicate issues (#210, #211, #212)

**Comment by Enivex** [comment]
As I commented on your issue, the different formula is intentional https://github.com/alex/nyt-2020-election-scraper/issues/194

The computation seems to break on flip, but that's a different issue.

**Comment by xxxmagicxxx** [comment]
```
Georgia (EV: 16) Total Votes: (Trump: 2,448,183, Biden: 2,447,518)
----------------  ---  ----------------  --------------------  -------------------------  ----------------  ----------------------------  ----------------
2020-11-06 08:40  ---  Trump up 463      Left (est.): 7,352    Δ:     306 (Biden +33.0%)  99.55% precincts  Biden needs 53.15% [-1.193%]  & trends  67.93%
2020-11-06 07:41  ---  Trump up 665      Left (est.): 7,658    Δ:     816 (Biden +36.9%)  99.55% precincts  Biden needs 54.34% [-3.134%]  & trends  67.86%
2020-11-06 06:41  ---  Trump up 1,267    Left (est.): 8,474    Δ:     541 (Biden +40.9%)  99.55% precincts  Biden needs 57.48% [-2.003%]  & trends  67.55%
```

**Comment by bojanrajkovic** [comment]
I think we fixed the hurdle calc in another PR. Can you confirm this is still needed?

**Comment by Enivex** [comment]
> I think we fixed the hurdle calc in another PR. Can you confirm this is still needed?

It's not needed. This reverts a commit that fixed an error in the formula (it did not take into account third parties).

**Pull request closed without merging**
